include:
    - pages
name: Calimania
tagline: Website for Kalima corporation
author: daveed
dest: build
copy:
    - public
exclude:
    - .draft.md
data:
    - data
theme:
    - layouts/tailwind
css: tailwind
engine: default
version: '2'
baseurl: https://dvidsilva.com
